# Generated by Django 4.1.4 on 2023-02-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='title',
            new_name='title_main',
        ),
    ]
