# Generated by Django 4.1.4 on 2023-02-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_title_tasks_title_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_slug',
            field=models.IntegerField(default=0),
        ),
    ]
